#!/usr/bin/env node

/**
 * Generates a .env.local file with all required secrets for SecureForm.
 * Run with: node scripts/generate-env.js
 *
 * Refuses to overwrite an existing .env.local unless --force is passed,
 * so you don't accidentally wipe out working secrets.
 */

const fs = require("fs");
const path = require("path");
const crypto = require("crypto");

const ENV_PATH = path.join(process.cwd(), ".env.local");
const FORCE = process.argv.includes("--force");

if (fs.existsSync(ENV_PATH) && !FORCE) {
  console.error(
    ".env.local already exists. Refusing to overwrite it.\n" +
      "If you really want to regenerate all secrets (this will invalidate\n" +
      "existing sessions and access links, and orphan your current data.json\n" +
      "if SERVER_KEY changes), run again with --force.",
  );
  process.exit(1);
}

// Access tokens: 16 bytes (128 bits) is plenty for an unguessable random
// token and keeps the shareable URL shorter than the original 24-byte version.
const generateToken = () => crypto.randomBytes(16).toString("base64url");

// Key material: kept at 32 bytes (256 bits) since these are actual
// cryptographic keys, not just access tokens.
const generateKey = () => crypto.randomBytes(32).toString("hex");

const adminToken = generateToken();
const respondentToken = generateToken();
const sessionSecret = generateKey();
const serverKey = generateKey();

const contents = `# Generated by scripts/generate-env.js — do not commit this file.
#
# ADMIN_TOKEN / RESPONDENT_TOKEN: secret URL tokens gating /admin/<token>
# and /answer/<token>. Share each with the relevant person over a channel
# separate from the passphrase.
ADMIN_TOKEN=${adminToken}
RESPONDENT_TOKEN=${respondentToken}

# SESSION_SECRET: encrypts the iron-session cookie itself (transport only,
# not your data).
SESSION_SECRET=${sessionSecret}

# SERVER_KEY: server-only secret used to independently unwrap the data
# encryption key for the respondent's session. Never exposed to either
# passphrase-holder. If this changes, existing data.json becomes unreadable
# via the respondent side (the admin passphrase path is unaffected).
SERVER_KEY=${serverKey}
`;

fs.writeFileSync(ENV_PATH, contents);

console.log("Created .env.local with freshly generated secrets.\n");
console.log("Your admin link token:      ", adminToken);
console.log("Your respondent link token: ", respondentToken);
console.log(
  "\nSave these somewhere safe if you need them outside this file. " +
    "They won't be shown again by this script.",
);
