import {
  Pencil,
  Trash2,
  Eye,
  EyeOff,
  LogOut,
  PlusCircle,
  CheckCircle,
  Save,
  Sparkles,
  Star,
  Heart,
  Moon,
  Sun,
  Lock,
  Unlock,
  MessageSquare,
  Send,
  BookOpen,
  ClipboardList,
  Feather,
  Flower2,
  Leaf,
  Flame,
  Gem,
  Bell,
  Circle,
  CircleStop,
  Square,
  SquareCheckBig,
} from "lucide-react";

export const iconOptions = {
  Pencil,
  Trash2,
  Eye,
  EyeOff,
  LogOut,
  PlusCircle,
  CheckCircle,
  Save,
  Sparkles,
  Star,
  Heart,
  Moon,
  Sun,
  Lock,
  Unlock,
  MessageSquare,
  Send,
  BookOpen,
  ClipboardList,
  Feather,
  Flower2,
  Leaf,
  Flame,
  Gem,
  Bell,
  Circle,
  CircleStop,
  Square,
  SquareCheckBig,
} as const;

export type IconName = keyof typeof iconOptions;

// Default icon assignment per UI slot
export const defaultIcons: Record<string, IconName> = {
  edit: "Pencil",
  delete: "Trash2",
  publish: "Eye",
  unpublish: "EyeOff",
  logout: "LogOut",
  addQuestion: "PlusCircle",
  saveIndicator: "CheckCircle",
  favicon: "Sparkles",
};

// Fixed selection-state icons — NOT user-configurable, not part of defaultIcons/theme picker
export const selectionIcons = {
  radio: "Circle",
  radioSelected: "CircleStop",
  checkbox: "Square",
  checkboxSelected: "SquareCheckBig",
} as const satisfies Record<string, IconName>;
